from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .manifest import WorkspaceManifest


@dataclass(frozen=True)
class WorkspaceSurfaceFiles:
    workspace_agents_path: Path | None
    workspace_docs_index_path: Path | None
    workspace_session_prompt_path: Path | None


def write_workspace_surface_files(
    *,
    manifest: WorkspaceManifest,
    workspace_path: Path,
    tenant_repo_path: Path,
    devkit_repo_path: Path,
    shared_addons_repo_path: Path | None,
) -> WorkspaceSurfaceFiles:
    workspace_agents_path: Path | None = None
    workspace_docs_index_path: Path | None = None
    workspace_session_prompt_path: Path | None = None

    if manifest.codex.workspace_agents:
        workspace_agents_path = workspace_path / "AGENTS.md"
        workspace_agents_path.write_text(
            _render_workspace_agents(
                manifest=manifest,
                workspace_path=workspace_path,
                tenant_repo_path=tenant_repo_path,
                devkit_repo_path=devkit_repo_path,
                shared_addons_repo_path=shared_addons_repo_path,
            ),
            encoding="utf-8",
        )

    if manifest.codex.workspace_docs_index:
        workspace_docs_index_path = workspace_path / "docs" / "README.md"
        workspace_docs_index_path.parent.mkdir(parents=True, exist_ok=True)
        workspace_docs_index_path.write_text(
            _render_workspace_docs_index(
                manifest=manifest,
                workspace_path=workspace_path,
                tenant_repo_path=tenant_repo_path,
                devkit_repo_path=devkit_repo_path,
                shared_addons_repo_path=shared_addons_repo_path,
            ),
            encoding="utf-8",
        )
        workspace_session_prompt_path = workspace_path / "docs" / "session-prompt.md"
        workspace_session_prompt_path.write_text(
            _render_workspace_session_prompt(
                workspace_path=workspace_path,
                tenant_repo_path=tenant_repo_path,
                devkit_repo_path=devkit_repo_path,
                shared_addons_repo_path=shared_addons_repo_path,
            ),
            encoding="utf-8",
        )

    return WorkspaceSurfaceFiles(
        workspace_agents_path=workspace_agents_path,
        workspace_docs_index_path=workspace_docs_index_path,
        workspace_session_prompt_path=workspace_session_prompt_path,
    )


def _render_workspace_agents(
    *,
    manifest: WorkspaceManifest,
    workspace_path: Path,
    tenant_repo_path: Path,
    devkit_repo_path: Path,
    shared_addons_repo_path: Path | None,
) -> str:
    shared_addons_source_path = shared_addons_repo_path.resolve() if shared_addons_repo_path is not None else None
    tenant_workspace_sync_command = _render_tenant_workspace_command(
        tenant_repo_path=tenant_repo_path,
        script_name="workspace-sync",
        fallback_command=f"uv --directory {devkit_repo_path} run platform workspace sync --manifest {manifest.manifest_path}",
    )
    tenant_workspace_status_command = _render_tenant_workspace_command(
        tenant_repo_path=tenant_repo_path,
        script_name="workspace-status",
        fallback_command=f"uv --directory {devkit_repo_path} run platform workspace status --manifest {manifest.manifest_path}",
    )
    shared_addons_source_of_truth = (
        f"- `sources/shared-addons/` resolves to `{shared_addons_source_path}`. Edit shared addon code in that source repo path, not by treating the workspace as the owner."
        if shared_addons_source_path is not None
        else "- No separate shared-addons source is materialized for this workspace yet."
    )
    shared_addons_pointer = (
        f"- `sources/shared-addons/` points to `{shared_addons_repo_path}`."
        if shared_addons_repo_path is not None
        else "- `sources/shared-addons/` is not present in this workspace."
    )
    return (
        "# AGENTS.md — Workspace Operating Guide\n\n"
        "This file is generated by `uv run platform workspace sync`. Treat the workspace root as the shared Every Code cockpit for this tenant while keeping hand-edited source-of-truth changes in the underlying repos.\n\n"
        "## Start Here\n\n"
        "- Open `docs/README.md` in this workspace root first. It routes to the shared devkit docs and the tenant-specific docs.\n"
        "- If present, open `AGENTS.override.md` for local, non-secret operator details before touching infra, SSH, tunnels, or remote service configuration. Keep secrets in `.env`.\n"
        "- For the deeper shared operating guide, open `sources/devkit/AGENTS.md`.\n"
        "- For workspace command details, open `sources/devkit/docs/tooling/workspace-cli.md`.\n"
        "- Use `sources/tenant/` for the active tenant source tree. PyCharm should still open that tenant repo directly by default.\n"
        "- Use `sources/devkit/` for shared DX/runtime/tooling ownership. That repo is the canonical owner of the shared operating guide and docs used to generate this workspace surface.\n"
        "- Treat `platform runtime` as the home for local runtime work plus explicit Dokploy-managed data workflows. Stable remote lanes are `testing` and `prod`; Launchplane PR previews replace a durable `dev` lane; release actions such as ship/promote/gate stay in `launchplane`.\n"
        f"{shared_addons_pointer}\n"
        "- Treat `.generated/` as managed output only. Treat `state/`, when present, as legacy or disposable local runtime output; it should not become a long-term home for hand-edited code or secrets.\n\n"
        "## Source Of Truth Rules\n\n"
        f"- Tenant handwritten code lives in `sources/tenant/` and resolves to `{tenant_repo_path}`.\n"
        f"- Shared DX/docs/runtime guidance lives in `sources/devkit/` and resolves to `{devkit_repo_path}`.\n"
        f"{shared_addons_source_of_truth}\n"
        "- Generated runtime files live under `.generated/`. Legacy or disposable local runtime output may live under `state/` when an older workspace still has it.\n"
        f"- The tracked manifest that defines this workspace is `{manifest.manifest_path}`.\n\n"
        "## Workspace Commands\n\n"
        f"- Resync this workspace with `{tenant_workspace_sync_command}`.\n"
        f"- Inspect workspace status with `{tenant_workspace_status_command}`.\n"
        "- Use the generated PyCharm run configurations from the tenant repo for infrequent but important workflows.\n\n"
        "## Editing Guardrails\n\n"
        "- Do not move source-of-truth docs or code into the workspace root just because Every Code starts here. The workspace root is a generated cockpit, not the canonical repo.\n"
        "- Keep tenant repo root docs thin and tenant-specific. Keep shared operating guidance in `odoo-devkit`, then surface it here during sync.\n"
        "- For non-trivial work, prefer small validated checkpoint commits in the source repos, use them as the base for review follow-ups, and clean up temporary branches/worktrees as you go. See `sources/devkit/AGENTS.md` for the shared workflow rule.\n"
        "- If a path is generated, prefer fixing the generator in `sources/devkit/` instead of editing the generated output directly.\n\n"
        "## Current Layout\n\n"
        f"- Workspace root: `{workspace_path}`\n"
        "- Tenant checkout: `sources/tenant/`\n"
        "- Shared devkit checkout: `sources/devkit/`\n"
        "- Shared addons checkout: `sources/shared-addons/` when declared\n"
        "- Generated runtime output: `.generated/`\n"
        "- Legacy or disposable local runtime output: `state/` when present\n"
    )


def _render_workspace_docs_index(
    *,
    manifest: WorkspaceManifest,
    workspace_path: Path,
    tenant_repo_path: Path,
    devkit_repo_path: Path,
    shared_addons_repo_path: Path | None,
) -> str:
    shared_addons_source_path = shared_addons_repo_path.resolve() if shared_addons_repo_path is not None else None
    tenant_workspace_sync_command = _render_tenant_workspace_command(
        tenant_repo_path=tenant_repo_path,
        script_name="workspace-sync",
        fallback_command=f"uv --directory {devkit_repo_path} run platform workspace sync --manifest {manifest.manifest_path}",
    )
    tenant_workspace_status_command = _render_tenant_workspace_command(
        tenant_repo_path=tenant_repo_path,
        script_name="workspace-status",
        fallback_command=f"uv --directory {devkit_repo_path} run platform workspace status --manifest {manifest.manifest_path}",
    )
    tenant_docs_line = _render_optional_link_line(
        label="Tenant docs",
        relative_target=Path("../sources/tenant/docs/README.md"),
        absolute_target=tenant_repo_path / "docs" / "README.md",
        fallback_text="Tenant docs index is not present yet; keep tenant-specific notes in the tenant repo.",
    )
    shared_devkit_docs_line = _render_optional_link_line(
        label="Shared devkit docs",
        relative_target=Path("../sources/devkit/docs/README.md"),
        absolute_target=devkit_repo_path / "docs" / "README.md",
        fallback_text="Shared devkit docs index is not present yet.",
    )
    shared_workspace_cli_line = _render_optional_link_line(
        label="Shared workspace CLI guide",
        relative_target=Path("../sources/devkit/docs/tooling/workspace-cli.md"),
        absolute_target=devkit_repo_path / "docs" / "tooling" / "workspace-cli.md",
        fallback_text="Shared workspace CLI guide is not present yet.",
    )
    shared_command_patterns_line = _render_optional_link_line(
        label="Shared workspace command patterns",
        relative_target=Path("../sources/devkit/docs/tooling/command-patterns.md"),
        absolute_target=devkit_repo_path / "docs" / "tooling" / "command-patterns.md",
        fallback_text="Shared workspace command-patterns guide is not present yet.",
    )
    shared_architecture_line = _render_optional_link_line(
        label="Shared workspace architecture",
        relative_target=Path("../sources/devkit/docs/ARCHITECTURE.md"),
        absolute_target=devkit_repo_path / "docs" / "ARCHITECTURE.md",
        fallback_text="Shared workspace architecture guide is not present yet.",
    )
    shared_roles_line = _render_optional_link_line(
        label="Shared roles guide",
        relative_target=Path("../sources/devkit/docs/roles.md"),
        absolute_target=devkit_repo_path / "docs" / "roles.md",
        fallback_text="Shared roles guide is not present yet.",
    )
    tenant_overlay_line = _render_optional_link_line(
        label="Tenant overlay guide",
        relative_target=Path("../sources/devkit/docs/tooling/tenant-overlay.md"),
        absolute_target=devkit_repo_path / "docs" / "tooling" / "tenant-overlay.md",
        fallback_text="Tenant overlay guide is not present yet.",
    )
    devkit_agents_line = _render_optional_link_line(
        label="Shared devkit guide",
        relative_target=Path("../sources/devkit/AGENTS.md"),
        absolute_target=devkit_repo_path / "AGENTS.md",
        fallback_text="Shared devkit AGENTS file is not present yet.",
    )
    shared_addons_line = (
        f"- Shared addons source repo: `../sources/shared-addons/` -> `{shared_addons_source_path}`\n"
        if shared_addons_source_path is not None
        else ""
    )
    session_prompt_line = "- [Session prompt template](session-prompt.md)\n"
    return (
        "# Workspace Docs\n\n"
        "This index is generated by `workspace sync`. Use it as the top-level Every Code map for the materialized workspace.\n\n"
        "## Primary Guides\n\n"
        "- [Workspace operating guide](../AGENTS.md)\n"
        f"{shared_devkit_docs_line}"
        f"{shared_architecture_line}"
        f"{shared_workspace_cli_line}"
        f"{shared_command_patterns_line}"
        f"{shared_roles_line}"
        f"{tenant_overlay_line}"
        f"{devkit_agents_line}"
        f"{tenant_docs_line}"
        f"{session_prompt_line}"
        "\n"
        "## Source Trees\n\n"
        f"- Tenant repo: `../sources/tenant/` -> `{tenant_repo_path}`\n"
        f"- Shared devkit repo: `../sources/devkit/` -> `{devkit_repo_path}`\n"
        f"{shared_addons_line}"
        "\n"
        "## Generated Runtime Files\n\n"
        "- [Generated Odoo config](../.generated/odoo.conf)\n"
        "- [Generated runtime env](../.generated/runtime.env)\n"
        "- [Generated PyCharm metadata](../.generated/pycharm/project-metadata.json)\n"
        "- [Workspace lock file](../workspace.lock.toml)\n"
        "\n"
        "## Working Agreement\n\n"
        f"- Every Code should start from this workspace root for `{manifest.tenant}` so shared docs and runtime context stay visible.\n"
        "- PyCharm should keep opening the tenant repo directly so search/indexing stays focused on the client code.\n"
        f"- Preferred tenant-root sync command: `{tenant_workspace_sync_command}`.\n"
        f"- Preferred tenant-root status command: `{tenant_workspace_status_command}`.\n"
        "- Treat `platform runtime` as the local-runtime and remote-data-workflow surface. Stable remote lanes are `testing` and `prod`; Launchplane PR previews replace a durable `dev` lane; release actions for remote environments belong in `launchplane`.\n"
        "- When in doubt about ownership, fix the source repo under `sources/` instead of editing generated files in the workspace root.\n"
    )


def _render_workspace_session_prompt(
    *,
    workspace_path: Path,
    tenant_repo_path: Path,
    devkit_repo_path: Path,
    shared_addons_repo_path: Path | None,
) -> str:
    shared_addons_source_path = shared_addons_repo_path.resolve() if shared_addons_repo_path is not None else None
    shared_addons_line = f"- sources/shared-addons -> {shared_addons_source_path}\n" if shared_addons_source_path is not None else ""
    return (
        "# Session Prompt Template\n\n"
        "Use this as a starting prompt for a new Every Code session from the generated workspace root.\n\n"
        "```text\n"
        "You are working from a generated Odoo workspace root.\n\n"
        "Start by reading:\n"
        "- AGENTS.md in the workspace root\n"
        "- docs/README.md in the workspace root\n\n"
        f"Working root:\n- {workspace_path}\n\n"
        "Source tree map:\n"
        f"- sources/tenant -> {tenant_repo_path}\n"
        f"- sources/devkit -> {devkit_repo_path}\n"
        f"{shared_addons_line}"
        "\n"
        "Working rules:\n"
        "- Treat the workspace root as a generated cockpit, not the source of truth.\n"
        "- Keep tenant code in sources/tenant.\n"
        "- Keep shared DX/runtime/workspace behavior in odoo-devkit.\n"
        "- Use platform runtime for local runtime and explicit data workflows.\n"
        "- Use launchplane for remote release actions.\n"
        "- Stable remote lanes are testing and prod.\n"
        "- Launchplane PR previews replace any durable shared dev lane.\n"
        "- When generated files disagree with source repos, fix the source repo or generator rather than hand-editing generated output.\n"
        "```\n"
    )


def _render_tenant_workspace_command(*, tenant_repo_path: Path, script_name: str, fallback_command: str) -> str:
    script_path = tenant_repo_path / "scripts" / script_name
    if script_path.exists():
        return f"sources/tenant/scripts/{script_name}"
    return fallback_command


def _render_optional_link_line(
    *,
    label: str,
    relative_target: Path,
    absolute_target: Path,
    fallback_text: str,
) -> str:
    if absolute_target.exists():
        return f"- [{label}]({relative_target.as_posix()})\n"
    return f"- {fallback_text}\n"
